/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/avatar-intro` | `/avatar-intro`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/complete` | `/complete`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/face-verification` | `/face-verification`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/manager-intro` | `/manager-intro`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/phone-verification` | `/phone-verification`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/questions` | `/questions`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(onboarding)'}/avatar-intro` | `/avatar-intro`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(onboarding)'}/complete` | `/complete`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(onboarding)'}/face-verification` | `/face-verification`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(onboarding)'}/manager-intro` | `/manager-intro`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(onboarding)'}/phone-verification` | `/phone-verification`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(onboarding)'}/questions` | `/questions`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(onboarding)'}/avatar-intro${`?${string}` | `#${string}` | ''}` | `/avatar-intro${`?${string}` | `#${string}` | ''}` | `${'/(onboarding)'}/complete${`?${string}` | `#${string}` | ''}` | `/complete${`?${string}` | `#${string}` | ''}` | `${'/(onboarding)'}/face-verification${`?${string}` | `#${string}` | ''}` | `/face-verification${`?${string}` | `#${string}` | ''}` | `${'/(onboarding)'}/manager-intro${`?${string}` | `#${string}` | ''}` | `/manager-intro${`?${string}` | `#${string}` | ''}` | `${'/(onboarding)'}/phone-verification${`?${string}` | `#${string}` | ''}` | `/phone-verification${`?${string}` | `#${string}` | ''}` | `${'/(onboarding)'}/questions${`?${string}` | `#${string}` | ''}` | `/questions${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/avatar-intro` | `/avatar-intro`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/complete` | `/complete`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/face-verification` | `/face-verification`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/manager-intro` | `/manager-intro`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/phone-verification` | `/phone-verification`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/questions` | `/questions`; params?: Router.UnknownInputParams; };
    }
  }
}
