-- ==========================================
-- FLIO Complete 44-Question Database
-- Research-based: Gottman Institute, Attachment Theory, Big Five, Korean marriage agencies (듀오, 가연)
-- Optimized based on psychological research (2024)
-- ==========================================

CREATE TABLE IF NOT EXISTS questions (
    id VARCHAR(100) PRIMARY KEY,
    category VARCHAR(50) NOT NULL,
    text_ko TEXT NOT NULL,
    text_en TEXT NOT NULL,
    answer_type VARCHAR(50) NOT NULL,
    options JSONB NOT NULL,
    base_weight FLOAT DEFAULT 0.5,
    effectiveness_score FLOAT DEFAULT 5.0,
    can_be_dealbreaker BOOLEAN DEFAULT false,
    tags TEXT[],
    placeholder TEXT,
    max_length INTEGER,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_questions_category ON questions(category);
CREATE INDEX IF NOT EXISTS idx_questions_effectiveness ON questions(effectiveness_score DESC);
CREATE INDEX IF NOT EXISTS idx_questions_active ON questions(is_active) WHERE is_active = TRUE;

CREATE TABLE IF NOT EXISTS question_performance (
    question_id VARCHAR(100) PRIMARY KEY REFERENCES questions(id) ON DELETE CASCADE,
    total_answers INTEGER DEFAULT 0,
    avg_importance FLOAT DEFAULT 0.0,
    dealbreaker_count INTEGER DEFAULT 0,
    last_answered_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

INSERT INTO questions (id, category, text_ko, text_en, answer_type, options, base_weight, effectiveness_score, can_be_dealbreaker, tags, placeholder, max_length) VALUES

-- DEALBREAKER QUESTIONS (4 core questions)
('gender_preference', '기본정보', '어떤 성별의 분을 만나고 싶으세요?', 'What gender would you like to meet?', 'choice', '[{"value": "male", "text_ko": "남성", "text_en": "Male", "match_weight": 1.0}, {"value": "female", "text_ko": "여성", "text_en": "Female", "match_weight": 1.0}, {"value": "any", "text_ko": "상관없어요", "text_en": "Any", "match_weight": 1.0}]'::jsonb, 1.0, 10.0, true, ARRAY['성별', '기본'], NULL, NULL),
('disability_acceptance', '가치관', '신체적 차이가 있는 분과의 연애에 대해 어떻게 생각하시나요?', 'How do you feel about dating someone with physical differences?', 'choice', '[{"value": "fully_open", "text_ko": "전혀 문제없어요", "text_en": "Completely open", "match_weight": 1.0}, {"value": "depends", "text_ko": "상황에 따라 달라요", "text_en": "Depends on situation", "match_weight": 0.5}, {"value": "prefer_not", "text_ko": "조금 어려울 것 같아요", "text_en": "Might be challenging", "match_weight": 0.0}]'::jsonb, 0.90, 9.8, true, ARRAY['포용'], NULL, NULL),
('divorce_status', '기본정보', '상대방의 이혼 경험에 대해 어떻게 생각하시나요?', 'How do you feel about a partner who has been divorced?', 'choice', '[{"value": "no_problem", "text_ko": "전혀 문제없어요", "text_en": "No problem at all", "match_weight": 1.0}, {"value": "depends", "text_ko": "상황에 따라 달라요", "text_en": "Depends on situation", "match_weight": 0.5}, {"value": "prefer_not", "text_ko": "선호하지 않아요", "text_en": "Prefer not", "match_weight": 0.0}]'::jsonb, 1.0, 10.0, true, ARRAY['이혼', '기본'], NULL, NULL),
('age_range_preference', '기본정보', '선호하는 상대방의 나이 범위는?', 'What is your preferred age range for a partner?', 'choice', '[{"value": "same_age", "text_ko": "동갑 ±2세", "text_en": "Same age ±2 years", "match_weight": 1.0}, {"value": "younger_5", "text_ko": "나보다 최대 5세 어려도 괜찮아요", "text_en": "Up to 5 years younger", "match_weight": 0.9}, {"value": "older_5", "text_ko": "나보다 최대 5세 많아도 괜찮아요", "text_en": "Up to 5 years older", "match_weight": 0.9}, {"value": "age_gap_ok", "text_ko": "나이 차이는 상관없어요", "text_en": "Age gap doesn''t matter", "match_weight": 0.8}]'::jsonb, 1.0, 10.0, true, ARRAY['나이', '기본'], NULL, NULL),

-- CORE QUESTIONS (Q1-5) - Use importance ratings, not dealbreakers
('marriage_timeline', '결혼계획', '결혼은 언제쯤 생각하고 계세요?', 'When are you thinking about marriage?', 'choice', '[{"value": "within_1_year", "text_ko": "1년 이내에 하고 싶어요", "text_en": "Within 1 year", "match_weight": 1.0}, {"value": "1_2_years", "text_ko": "1-2년 정도 생각해요", "text_en": "1-2 years", "match_weight": 0.95}, {"value": "2_3_years", "text_ko": "2-3년 후에요", "text_en": "2-3 years", "match_weight": 0.85}, {"value": "3_5_years", "text_ko": "3년 이상 후에요", "text_en": "3+ years later", "match_weight": 0.7}, {"value": "not_decided", "text_ko": "아직 생각 중이에요", "text_en": "Still thinking", "match_weight": 0.5}]'::jsonb, 0.95, 10.0, false, ARRAY['결혼', '시기'], NULL, NULL),
('children_plan', '결혼계획', '결혼 후 자녀 계획은 어떻게 생각하세요?', 'What are your thoughts on having children?', 'choice', '[{"value": "want_2_3", "text_ko": "2-3명 갖고 싶어요", "text_en": "Would like 2-3", "match_weight": 1.0}, {"value": "want_1", "text_ko": "1명 갖고 싶어요", "text_en": "Would like 1", "match_weight": 0.85}, {"value": "undecided", "text_ko": "아직 생각 중이에요", "text_en": "Still thinking", "match_weight": 0.6}, {"value": "no_children", "text_ko": "자녀 없이 살고 싶어요", "text_en": "Prefer no children", "match_weight": 0.3}]'::jsonb, 0.95, 9.9, false, ARRAY['자녀'], NULL, NULL),
('conflict_resolution', '갈등해결', '연인과 심하게 다투었을 때, 어떻게 해결하시나요?', 'How do you resolve serious disagreements with your partner?', 'choice', '[{"value": "calm_discussion", "text_ko": "마음을 진정시킨 후 대화해요", "text_en": "Calm down first, then talk", "match_weight": 1.0}, {"value": "immediate_talk", "text_ko": "바로 대화로 풀어요", "text_en": "Talk it out immediately", "match_weight": 0.95}, {"value": "need_time", "text_ko": "혼자 생각할 시간이 필요해요", "text_en": "Need time to think alone", "match_weight": 0.7}, {"value": "avoid", "text_ko": "갈등 상황을 피하는 편이에요", "text_en": "Tend to avoid conflict", "match_weight": 0.3}]'::jsonb, 0.95, 9.7, false, ARRAY['갈등'], NULL, NULL),
('trust_jealousy', '갈등해결', '연인이 이성 친구와 단둘이 만난다면 어떻게 느끼세요?', 'How would you feel if your partner met a friend of the opposite gender alone?', 'choice', '[{"value": "trust_fully", "text_ko": "전적으로 믿어요", "text_en": "Completely trust them", "match_weight": 1.0}, {"value": "express_feeling", "text_ko": "솔직하게 제 마음을 표현해요", "text_en": "Express my feelings honestly", "match_weight": 0.95}, {"value": "ask_details", "text_ko": "어떤 분인지 여쭤볼 것 같아요", "text_en": "Would ask about them", "match_weight": 0.85}, {"value": "feel_anxious", "text_ko": "조금 불안하지만 참을 것 같아요", "text_en": "A bit anxious but would endure", "match_weight": 0.5}, {"value": "cannot_accept", "text_ko": "솔직히 받아들이기 어려워요", "text_en": "Honestly difficult to accept", "match_weight": 0.2}]'::jsonb, 0.90, 9.5, false, ARRAY['신뢰'], NULL, NULL),

-- GOTTMAN'S FOUR HORSEMEN (New - Research-based: 94% divorce prediction accuracy)
('criticism_expression', '갈등해결', '연인에게 불만이 있을 때 어떻게 표현하시나요?', 'How do you express frustration with your partner?', 'choice', '[{"value": "gentle_request", "text_ko": "부드럽게 요청을 해요", "text_en": "Make gentle requests", "match_weight": 1.0}, {"value": "use_i_statements", "text_ko": "\"나는 ~해\"로 감정을 표현해요", "text_en": "Use \"I feel...\" statements", "match_weight": 0.95}, {"value": "point_out_issue", "text_ko": "문제를 지적해요", "text_en": "Point out the issue", "match_weight": 0.6}, {"value": "criticize_character", "text_ko": "상대의 성격이나 태도를 비판해요", "text_en": "Criticize their character", "match_weight": 0.2}]'::jsonb, 0.95, 9.6, false, ARRAY['갈등', 'Gottman'], NULL, NULL),
('partner_mistake_reaction', '갈등해결', '연인이 실수했을 때 첫 반응은 어떠세요?', 'What is your first reaction when your partner makes a mistake?', 'choice', '[{"value": "understanding", "text_ko": "이해하고 격려해요", "text_en": "Show understanding and encouragement", "match_weight": 1.0}, {"value": "discuss_calmly", "text_ko": "차분하게 이야기해요", "text_en": "Discuss it calmly", "match_weight": 0.95}, {"value": "disappointed", "text_ko": "실망감을 느껴요", "text_en": "Feel disappointed", "match_weight": 0.5}, {"value": "mock_or_belittle", "text_ko": "놀리거나 무시하는 말을 해요", "text_en": "Mock or belittle them", "match_weight": 0.1}]'::jsonb, 0.95, 9.5, false, ARRAY['갈등', 'Gottman'], NULL, NULL),
('argument_reconnection', '갈등해결', '다툰 후 어떻게 다시 가까워지시나요?', 'How do you reconnect after an argument?', 'choice', '[{"value": "apologize_first", "text_ko": "먼저 사과하고 대화해요", "text_en": "Apologize first and talk", "match_weight": 1.0}, {"value": "use_humor", "text_ko": "유머로 분위기를 풀어요", "text_en": "Use humor to lighten the mood", "match_weight": 0.9}, {"value": "give_affection", "text_ko": "스킨십으로 풀어요", "text_en": "Reconnect through affection", "match_weight": 0.85}, {"value": "wait_until_calm", "text_ko": "시간이 지나면 자연스럽게 풀려요", "text_en": "Wait until things naturally calm down", "match_weight": 0.6}]'::jsonb, 0.90, 9.4, false, ARRAY['갈등', 'Gottman'], NULL, NULL),

-- ATTACHMENT SECURITY (New - Research-based: 90%+ prediction accuracy)
('good_news_response', '감정지원', '좋은 소식을 나눴을 때 어떤 반응을 받으면 가장 행복하세요?', 'When sharing good news, what response makes you feel closest?', 'choice', '[{"value": "enthusiastic_celebration", "text_ko": "진심으로 기뻐하며 함께 축하해줘요", "text_en": "Enthusiastically celebrate together", "match_weight": 1.0}, {"value": "ask_details", "text_ko": "자세히 물어보며 관심을 보여요", "text_en": "Ask for details and show interest", "match_weight": 0.95}, {"value": "quiet_support", "text_ko": "조용히 지지해줘요", "text_en": "Quietly supportive", "match_weight": 0.7}, {"value": "point_out_concerns", "text_ko": "걱정되는 점을 먼저 이야기해요", "text_en": "Point out potential concerns", "match_weight": 0.3}]'::jsonb, 0.90, 9.3, false, ARRAY['감정', 'Attachment'], NULL, NULL),
('disagreement_comfort', '갈등해결', '연인과 의견이 다를 때 얼마나 편안하세요?', 'How comfortable are you with disagreements in relationships?', 'choice', '[{"value": "very_comfortable", "text_ko": "편안해요, 건강한 대화라고 생각해요", "text_en": "Very comfortable, see it as healthy", "match_weight": 1.0}, {"value": "okay_with_minor", "text_ko": "작은 의견 차이는 괜찮아요", "text_en": "Okay with minor differences", "match_weight": 0.8}, {"value": "somewhat_anxious", "text_ko": "조금 불안하지만 해결하려 노력해요", "text_en": "Somewhat anxious but try to resolve", "match_weight": 0.6}, {"value": "very_uncomfortable", "text_ko": "매우 불편하고 피하고 싶어요", "text_en": "Very uncomfortable, want to avoid", "match_weight": 0.2}]'::jsonb, 0.90, 9.2, false, ARRAY['갈등', 'Attachment'], NULL, NULL),

-- KOREAN CULTURAL PRIORITIES (New - 82% consider family approval critical)
('family_approval_importance', '가족', '연애에서 가족의 동의가 얼마나 중요하세요?', 'How important is family approval for your relationship?', 'choice', '[{"value": "very_important", "text_ko": "매우 중요해요, 꼭 받고 싶어요", "text_en": "Very important, must have it", "match_weight": 1.0}, {"value": "important", "text_ko": "중요하지만 최종 결정은 제가 해요", "text_en": "Important but I make final decision", "match_weight": 0.8}, {"value": "prefer_approval", "text_ko": "있으면 좋지만 필수는 아니에요", "text_en": "Nice to have but not required", "match_weight": 0.5}, {"value": "not_important", "text_ko": "크게 중요하지 않아요", "text_en": "Not very important", "match_weight": 0.2}]'::jsonb, 0.90, 9.1, false, ARRAY['가족', '한국문화'], NULL, NULL),
('parental_role_expectations', '가족', '결혼 후 부모님이 어떤 역할을 하시길 바라세요?', 'What role do you expect parents to play in married life?', 'choice', '[{"value": "close_involvement", "text_ko": "가까이 지내며 많이 도와주셨으면 해요", "text_en": "Close involvement and support", "match_weight": 1.0}, {"value": "regular_visits", "text_ko": "정기적으로 뵙고 중요한 일은 상의해요", "text_en": "Regular visits, consult on important matters", "match_weight": 0.85}, {"value": "occasional_contact", "text_ko": "가끔 뵙고 독립적으로 살고 싶어요", "text_en": "Occasional contact, live independently", "match_weight": 0.6}, {"value": "minimal_involvement", "text_ko": "최소한의 관여를 원해요", "text_en": "Prefer minimal involvement", "match_weight": 0.3}]'::jsonb, 0.85, 9.0, false, ARRAY['가족', '한국문화'], NULL, NULL),
('traditional_modern_balance', '가치관', '전통적 가치와 현대적 관계관 중 어디에 가까우세요?', 'How do you balance traditional and modern relationship values?', 'choice', '[{"value": "traditional", "text_ko": "전통적 가치를 중시해요", "text_en": "Value traditional approach", "match_weight": 1.0}, {"value": "balanced", "text_ko": "전통과 현대를 균형있게 해요", "text_en": "Balance both traditional and modern", "match_weight": 0.9}, {"value": "modern", "text_ko": "현대적 관계관을 선호해요", "text_en": "Prefer modern approach", "match_weight": 0.7}, {"value": "fully_modern", "text_ko": "완전히 현대적으로 살고 싶어요", "text_en": "Fully modern lifestyle", "match_weight": 0.5}]'::jsonb, 0.85, 8.9, false, ARRAY['가치관', '한국문화'], NULL, NULL),

-- RELATIONSHIP DYNAMICS (Q6-15)
('emotional_support', '감정지원', '연인이 힘들어할 때 어떻게 해주시나요?', 'How do you support your partner when they are struggling?', 'choice', '[{"value": "listen_empathize", "text_ko": "공감하며 이야기를 들어줘요", "text_en": "Listen with empathy", "match_weight": 1.0}, {"value": "give_solution", "text_ko": "해결책을 함께 찾아봐요", "text_en": "Help find solutions", "match_weight": 0.8}, {"value": "cheer_up", "text_ko": "기분 전환을 도와줘요", "text_en": "Help cheer them up", "match_weight": 0.7}, {"value": "give_space", "text_ko": "혼자 생각할 시간을 줘요", "text_en": "Give them space", "match_weight": 0.6}]'::jsonb, 0.85, 9.0, false, ARRAY['감정'], NULL, NULL),
('communication_frequency', '소통', '연인과 얼마나 자주 연락하고 만나고 싶으세요?', 'How often would you like to communicate and meet your partner?', 'choice', '[{"value": "constant_and_daily", "text_ko": "수시로 연락하고 거의 매일 만나요", "text_en": "Constant contact and meet almost daily", "match_weight": 1.0}, {"value": "daily_and_frequent", "text_ko": "매일 연락하고 주 4-5회 만나요", "text_en": "Daily contact and meet 4-5 times/week", "match_weight": 0.9}, {"value": "regular", "text_ko": "하루 한 번 연락하고 주 2-3회 만나요", "text_en": "Contact once daily and meet 2-3 times/week", "match_weight": 0.75}, {"value": "moderate", "text_ko": "주 2-3회 연락하고 주 1회 만나요", "text_en": "Contact 2-3 times/week and meet once weekly", "match_weight": 0.5}]'::jsonb, 0.80, 8.5, false, ARRAY['소통'], NULL, NULL),
('attachment_style', '애착', '연애할 때 어떤 애착 스타일인가요?', 'What is your attachment style in relationships?', 'choice', '[{"value": "secure", "text_ko": "안정적이고 편안하게 신뢰해요", "text_en": "Secure and trust comfortably", "match_weight": 1.0}, {"value": "anxious", "text_ko": "상대방 반응에 민감하고 확신을 원해요", "text_en": "Sensitive to reactions, need reassurance", "match_weight": 0.7}, {"value": "avoidant", "text_ko": "독립성을 중시하고 거리감이 필요해요", "text_en": "Value independence, need distance", "match_weight": 0.6}, {"value": "not_sure", "text_ko": "아직 잘 모르겠어요", "text_en": "Not sure yet", "match_weight": 0.5}]'::jsonb, 0.85, 8.8, false, ARRAY['애착'], NULL, NULL),
('love_language', '애정표현', '언제 가장 사랑받는다고 느끼세요?', 'When do you feel most loved?', 'choice', '[{"value": "words", "text_ko": "사랑한다는 말을 들을 때요", "text_en": "When I hear words of affirmation", "match_weight": 1.0}, {"value": "quality_time", "text_ko": "함께 시간을 보낼 때요", "text_en": "When we spend quality time together", "match_weight": 0.95}, {"value": "physical_touch", "text_ko": "스킨십을 할 때요", "text_en": "Through physical affection", "match_weight": 0.9}, {"value": "acts_service", "text_ko": "배려하는 행동을 받을 때요", "text_en": "When they do thoughtful things", "match_weight": 0.85}, {"value": "gifts", "text_ko": "선물을 받을 때요", "text_en": "When I receive gifts", "match_weight": 0.8}]'::jsonb, 0.80, 8.6, false, ARRAY['애정'], NULL, NULL),
('anniversary_importance', '기념일', '기념일을 얼마나 중요하게 생각하세요?', 'How important are anniversaries to you?', 'choice', '[{"value": "very_important", "text_ko": "매우 중요해요, 꼭 챙겨요", "text_en": "Very important, always celebrate", "match_weight": 1.0}, {"value": "important", "text_ko": "중요해요, 챙기려고 노력해요", "text_en": "Important, try to celebrate", "match_weight": 0.9}, {"value": "moderate", "text_ko": "기억하면 챙겨요", "text_en": "Celebrate if I remember", "match_weight": 0.6}, {"value": "not_important", "text_ko": "크게 신경 쓰지 않아요", "text_en": "Don''t focus on it much", "match_weight": 0.3}]'::jsonb, 0.70, 7.5, false, ARRAY['기념일'], NULL, NULL),
('future_planning', '미래', '미래 계획에 대해 의견이 다를 때 어떻게 하세요?', 'How do you handle disagreements about future plans?', 'choice', '[{"value": "thorough_discussion", "text_ko": "충분히 대화하며 토론해요", "text_en": "Discuss thoroughly together", "match_weight": 1.0}, {"value": "compromise", "text_ko": "서로 양보하며 조율해요", "text_en": "Compromise with each other", "match_weight": 0.95}, {"value": "practical_choice", "text_ko": "현실적인 선택을 해요", "text_en": "Make practical choices", "match_weight": 0.8}, {"value": "take_time", "text_ko": "천천히 시간을 두고 결정해요", "text_en": "Take time to decide", "match_weight": 0.75}]'::jsonb, 0.85, 8.7, false, ARRAY['미래'], NULL, NULL),
('social_life_balance', '사회생활', '친구들과 얼마나 자주 만나세요?', 'How often do you meet with friends?', 'choice', '[{"value": "weekly", "text_ko": "주 1회 이상 만나요", "text_en": "Once a week or more", "match_weight": 1.0}, {"value": "biweekly", "text_ko": "2주에 1회 정도요", "text_en": "About every two weeks", "match_weight": 0.9}, {"value": "monthly", "text_ko": "한 달에 1-2회 정도요", "text_en": "Once or twice a month", "match_weight": 0.7}, {"value": "rarely", "text_ko": "거의 안 만나는 편이에요", "text_en": "Rarely meet up", "match_weight": 0.5}]'::jsonb, 0.70, 7.2, false, ARRAY['사회생활'], NULL, NULL),
('physical_affection', '스킨십', '스킨십은 얼마나 중요하세요?', 'How important is physical affection to you?', 'choice', '[{"value": "very_important", "text_ko": "매우 중요해요", "text_en": "Very important", "match_weight": 1.0}, {"value": "important", "text_ko": "중요한 편이에요", "text_en": "Quite important", "match_weight": 0.9}, {"value": "moderate", "text_ko": "적당히 좋아요", "text_en": "Moderately important", "match_weight": 0.7}, {"value": "minimal", "text_ko": "최소한이면 충분해요", "text_en": "Minimal is enough", "match_weight": 0.4}]'::jsonb, 0.75, 7.9, false, ARRAY['스킨십'], NULL, NULL),

-- FAMILY & VALUES (Q16-25)
('parents_relationship', '가족', '부모님과의 관계는 어떠세요?', 'How is your relationship with your parents?', 'choice', '[{"value": "very_close", "text_ko": "매우 친밀해요", "text_en": "Very close", "match_weight": 1.0}, {"value": "close", "text_ko": "친밀한 편이에요", "text_en": "Quite close", "match_weight": 0.9}, {"value": "moderate", "text_ko": "보통이에요", "text_en": "Average", "match_weight": 0.7}, {"value": "distant", "text_ko": "약간 거리감이 있어요", "text_en": "Somewhat distant", "match_weight": 0.5}]'::jsonb, 0.80, 8.3, false, ARRAY['가족'], NULL, NULL),
('holiday_obligations', '명절', '명절에 양가 방문은 어떻게 생각하세요?', 'How do you feel about visiting both families during holidays?', 'choice', '[{"value": "visit_both", "text_ko": "양가 모두 방문하고 싶어요", "text_en": "Want to visit both", "match_weight": 1.0}, {"value": "alternate", "text_ko": "번갈아 방문하면 좋겠어요", "text_en": "Prefer alternating", "match_weight": 0.9}, {"value": "new_way", "text_ko": "새로운 방식을 만들고 싶어요", "text_en": "Want to create new traditions", "match_weight": 0.75}, {"value": "flexible", "text_ko": "상황에 따라 유연하게요", "text_en": "Flexible depending on situation", "match_weight": 0.5}]'::jsonb, 0.85, 8.6, false, ARRAY['명절'], NULL, NULL),
('financial_transparency', '재정', '결혼 후 재정 관리와 금전에 대한 태도는 어떠세요?', 'What is your approach to finances and money management in marriage?', 'choice', '[{"value": "fully_shared_saving", "text_ko": "완전 공동관리하며 저축을 중시해요", "text_en": "Fully shared, prioritize saving", "match_weight": 1.0}, {"value": "mostly_shared_balanced", "text_ko": "대부분 공동으로 균형있게 관리해요", "text_en": "Mostly shared, balanced approach", "match_weight": 0.95}, {"value": "proportional_practical", "text_ko": "수입 비율로 분담하고 실용적이에요", "text_en": "Split by income, practical", "match_weight": 0.75}, {"value": "separate_flexible", "text_ko": "각자 관리하고 유연하게 써요", "text_en": "Separate management, flexible spending", "match_weight": 0.5}]'::jsonb, 0.85, 8.8, false, ARRAY['재정'], NULL, NULL),
('career_priority', '커리어', '일과 가정, 그리고 인생 목표의 우선순위는 어떻게 생각하세요?', 'How do you prioritize work, family, and life goals?', 'choice', '[{"value": "family_happiness", "text_ko": "가정의 행복이 최우선이에요", "text_en": "Family happiness comes first", "match_weight": 1.0}, {"value": "balanced_all", "text_ko": "일, 가정, 개인성장 모두 균형있게요", "text_en": "Balance work, family, and personal growth", "match_weight": 0.95}, {"value": "career_important", "text_ko": "커리어 성공도 중요해요", "text_en": "Career success is also important", "match_weight": 0.8}, {"value": "career_first", "text_ko": "커리어를 우선시해요", "text_en": "Career comes first", "match_weight": 0.6}]'::jsonb, 0.85, 8.7, false, ARRAY['커리어', '목표'], NULL, NULL),
('household_division', '가사', '가사 분담은 어떻게 하고 싶으세요?', 'How would you like to divide household chores?', 'choice', '[{"value": "equal_split", "text_ko": "동등하게 나누고 싶어요", "text_en": "Want to split equally", "match_weight": 1.0}, {"value": "flexible", "text_ko": "상황에 따라 유연하게요", "text_en": "Flexible based on situation", "match_weight": 0.9}, {"value": "by_strength", "text_ko": "각자 잘하는 것을 맡아요", "text_en": "Each does what they''re good at", "match_weight": 0.8}, {"value": "hire_help", "text_ko": "도우미를 고용하고 싶어요", "text_en": "Would like to hire help", "match_weight": 0.7}]'::jsonb, 0.80, 8.4, false, ARRAY['가사'], NULL, NULL),
('religion_spirituality', '종교', '종교는 얼마나 중요하세요?', 'How important is religion to you?', 'choice', '[{"value": "very_important", "text_ko": "매우 중요해요", "text_en": "Very important", "match_weight": 1.0}, {"value": "somewhat", "text_ko": "어느 정도 중요해요", "text_en": "Somewhat important", "match_weight": 0.7}, {"value": "not_important", "text_ko": "크게 중요하지 않아요", "text_en": "Not very important", "match_weight": 0.3}, {"value": "respect_all", "text_ko": "모든 종교를 존중해요", "text_en": "Respect all religions", "match_weight": 0.8}]'::jsonb, 0.75, 7.8, false, ARRAY['종교'], NULL, NULL),
('political_views', '정치', '정치에 대한 생각은 어떠세요?', 'What are your thoughts on politics?', 'choice', '[{"value": "progressive", "text_ko": "진보적인 편이에요", "text_en": "Tend to be progressive", "match_weight": 1.0}, {"value": "moderate", "text_ko": "중도적이에요", "text_en": "Moderate", "match_weight": 0.8}, {"value": "conservative", "text_ko": "보수적인 편이에요", "text_en": "Tend to be conservative", "match_weight": 0.6}, {"value": "not_interested", "text_ko": "크게 관심 없어요", "text_en": "Not very interested", "match_weight": 0.5}]'::jsonb, 0.70, 7.3, false, ARRAY['정치'], NULL, NULL),
('environmental_values', '환경', '환경보호에 얼마나 관심이 있으세요?', 'How concerned are you about the environment?', 'choice', '[{"value": "very_active", "text_ko": "적극적으로 실천해요", "text_en": "Actively practice", "match_weight": 1.0}, {"value": "try_best", "text_ko": "노력하는 편이에요", "text_en": "Try my best", "match_weight": 0.9}, {"value": "basic_only", "text_ko": "기본적인 것만 해요", "text_en": "Do the basics", "match_weight": 0.6}, {"value": "not_priority", "text_ko": "크게 신경 쓰지 않아요", "text_en": "Don''t focus on it much", "match_weight": 0.3}]'::jsonb, 0.65, 6.8, false, ARRAY['환경'], NULL, NULL),

-- LIFESTYLE (Q26-35)
('living_location', '주거', '어디에서 살고 싶으세요?', 'Where would you like to live?', 'choice', '[{"value": "city_center", "text_ko": "도심이 좋아요", "text_en": "Prefer city center", "match_weight": 1.0}, {"value": "suburb", "text_ko": "교외가 좋아요", "text_en": "Prefer suburbs", "match_weight": 0.8}, {"value": "countryside", "text_ko": "시골이 좋아요", "text_en": "Prefer countryside", "match_weight": 0.6}, {"value": "flexible", "text_ko": "어디든 괜찮아요", "text_en": "Anywhere is fine", "match_weight": 0.9}]'::jsonb, 0.75, 7.7, false, ARRAY['주거'], NULL, NULL),
('pet_preference', '반려동물', '반려동물에 대해 어떻게 생각하세요?', 'How do you feel about pets?', 'choice', '[{"value": "love_pets", "text_ko": "좋아해요, 키우고 싶어요", "text_en": "Love them, want to have pets", "match_weight": 1.0}, {"value": "okay_with", "text_ko": "괜찮아요", "text_en": "Fine with them", "match_weight": 0.8}, {"value": "prefer_not", "text_ko": "선호하지 않아요", "text_en": "Prefer not to have", "match_weight": 0.4}, {"value": "allergic", "text_ko": "알러지가 있어요", "text_en": "Have allergies", "match_weight": 0.2}]'::jsonb, 0.70, 7.1, false, ARRAY['반려동물'], NULL, NULL),
('exercise_habits', '운동', '운동은 얼마나 자주 하세요?', 'How often do you exercise?', 'choice', '[{"value": "daily", "text_ko": "거의 매일 해요", "text_en": "Almost daily", "match_weight": 1.0}, {"value": "regular", "text_ko": "주 3-4회 정도요", "text_en": "3-4 times a week", "match_weight": 0.9}, {"value": "sometimes", "text_ko": "가끔 해요", "text_en": "Sometimes", "match_weight": 0.6}, {"value": "rarely", "text_ko": "거의 안 하는 편이에요", "text_en": "Rarely exercise", "match_weight": 0.3}]'::jsonb, 0.65, 6.9, false, ARRAY['운동'], NULL, NULL),
('drinking_habits', '음주', '술은 얼마나 자주 드세요?', 'How often do you drink alcohol?', 'choice', '[{"value": "never", "text_ko": "마시지 않아요", "text_en": "Don''t drink", "match_weight": 1.0}, {"value": "social", "text_ko": "사교적으로만 마셔요", "text_en": "Only socially", "match_weight": 0.9}, {"value": "weekly", "text_ko": "주 1-2회 정도요", "text_en": "1-2 times a week", "match_weight": 0.7}, {"value": "frequent", "text_ko": "자주 마시는 편이에요", "text_en": "Drink frequently", "match_weight": 0.4}]'::jsonb, 0.80, 8.0, false, ARRAY['음주'], NULL, NULL),
('smoking_status', '흡연', '흡연은 하세요?', 'Do you smoke?', 'choice', '[{"value": "non_smoker", "text_ko": "피우지 않아요", "text_en": "Don''t smoke", "match_weight": 1.0}, {"value": "quit", "text_ko": "금연했어요", "text_en": "Quit smoking", "match_weight": 0.85}, {"value": "occasional", "text_ko": "가끔 피워요", "text_en": "Occasionally", "match_weight": 0.5}, {"value": "regular", "text_ko": "피우는 편이에요", "text_en": "Smoke regularly", "match_weight": 0.2}]'::jsonb, 0.85, 8.3, false, ARRAY['흡연'], NULL, NULL),
('travel_preference', '여행', '여행 스타일은 어떠세요?', 'What is your travel style?', 'choice', '[{"value": "adventure", "text_ko": "모험적인 여행을 좋아해요", "text_en": "Love adventurous trips", "match_weight": 1.0}, {"value": "cultural", "text_ko": "문화 탐방을 좋아해요", "text_en": "Enjoy cultural exploration", "match_weight": 0.9}, {"value": "relaxation", "text_ko": "휴양 위주로 좋아해요", "text_en": "Prefer relaxing trips", "match_weight": 0.8}, {"value": "not_interested", "text_ko": "여행을 별로 좋아하지 않아요", "text_en": "Not really into traveling", "match_weight": 0.4}]'::jsonb, 0.70, 7.4, false, ARRAY['여행'], NULL, NULL),
('food_preference', '음식', '음식 취향은 어떠세요?', 'What are your food preferences?', 'choice', '[{"value": "adventurous", "text_ko": "다양한 음식에 도전해요", "text_en": "Try diverse foods", "match_weight": 1.0}, {"value": "open_minded", "text_ko": "열린 마음으로 먹어요", "text_en": "Open to trying new things", "match_weight": 0.9}, {"value": "selective", "text_ko": "좋아하는 것 위주로 먹어요", "text_en": "Prefer what I like", "match_weight": 0.6}, {"value": "picky", "text_ko": "조금 까다로운 편이에요", "text_en": "A bit picky", "match_weight": 0.4}]'::jsonb, 0.65, 6.7, false, ARRAY['음식'], NULL, NULL),
('cleanliness', '청결', '청결에 대한 기준은 어떠세요?', 'What are your cleanliness standards?', 'choice', '[{"value": "very_clean", "text_ko": "매우 깔끔해야 해요", "text_en": "Need it very clean", "match_weight": 1.0}, {"value": "clean", "text_ko": "깔끔한 편이에요", "text_en": "Prefer it clean", "match_weight": 0.9}, {"value": "moderate", "text_ko": "보통이에요", "text_en": "Average standards", "match_weight": 0.7}, {"value": "relaxed", "text_ko": "여유로운 편이에요", "text_en": "Pretty relaxed about it", "match_weight": 0.5}]'::jsonb, 0.75, 7.6, false, ARRAY['청결'], NULL, NULL),
('introvert_extrovert', '성격', '성격 유형은 어떠세요?', 'What is your personality type?', 'choice', '[{"value": "extrovert", "text_ko": "외향적인 편이에요", "text_en": "More extroverted", "match_weight": 1.0}, {"value": "ambivert", "text_ko": "상황에 따라 달라요", "text_en": "Depends on the situation", "match_weight": 0.9}, {"value": "introvert", "text_ko": "내향적인 편이에요", "text_en": "More introverted", "match_weight": 0.7}]'::jsonb, 0.75, 7.8, false, ARRAY['성격'], NULL, NULL),

-- TEXT QUESTIONS (Q36-38) - Reduced from 5 to 3
('personal_values_lifestyle', '가치관', '당신의 삶에서 가장 중요한 가치는 무엇이며, 어떤 순간에 행복을 느끼시나요?', 'What values are most important in your life, and when do you feel happiest?', 'text', '[]'::jsonb, 0.95, 9.9, false, ARRAY['가치관', '일상', '행복'], '예: 성실함을 중요하게 여겨 매일 아침 운동하고, 가족과 함께 식사할 때 가장 행복해요...', 450),
('ideal_relationship_dynamic', '연애관', '이상적인 연애 관계는 어떤 모습이며, 5-10년 후 파트너와 어떤 삶을 살고 싶으세요?', 'What is your ideal relationship, and what life do you envision with your partner in 5-10 years?', 'text', '[]'::jsonb, 0.95, 9.8, false, ARRAY['연애', '관계', '미래', '비전'], '예: 서로의 꿈을 응원하면서도 함께하는 시간을 소중히 여기고, 10년 후엔 아이 둘과 함께 교외에 살며...', 450),
('conflict_growth_philosophy', '성장', '관계에서 어려움이나 갈등이 생겼을 때, 어떻게 극복하고 성장해왔나요?', 'How have you overcome difficulties in relationships and grown from them?', 'text', '[]'::jsonb, 0.90, 9.4, false, ARRAY['갈등', '성장'], '예: 과거엔 감정을 숨겼지만, 이제는 솔직하게 표현하고 함께 해결책을 찾으려 노력해요...', 350);

INSERT INTO question_performance (question_id)
SELECT id FROM questions
ON CONFLICT (question_id) DO NOTHING;
