-- ==========================================
-- FLIO Complete 40-Question Database
-- Research-based: Gottman Institute, Attachment Theory, Big Five, Korean marriage agencies (듀오, 가연)
-- ==========================================

CREATE TABLE IF NOT EXISTS questions (
    id VARCHAR(100) PRIMARY KEY,
    category VARCHAR(50) NOT NULL,
    text_ko TEXT NOT NULL,
    text_en TEXT NOT NULL,
    answer_type VARCHAR(50) NOT NULL,
    options JSONB NOT NULL,
    base_weight FLOAT DEFAULT 0.5,
    effectiveness_score FLOAT DEFAULT 5.0,
    can_be_dealbreaker BOOLEAN DEFAULT false,
    tags TEXT[],
    placeholder TEXT,
    max_length INTEGER,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_questions_category ON questions(category);
CREATE INDEX IF NOT EXISTS idx_questions_effectiveness ON questions(effectiveness_score DESC);
CREATE INDEX IF NOT EXISTS idx_questions_active ON questions(is_active) WHERE is_active = TRUE;

CREATE TABLE IF NOT EXISTS question_performance (
    question_id VARCHAR(100) PRIMARY KEY REFERENCES questions(id) ON DELETE CASCADE,
    total_answers INTEGER DEFAULT 0,
    avg_importance FLOAT DEFAULT 0.0,
    dealbreaker_count INTEGER DEFAULT 0,
    last_answered_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

INSERT INTO questions (id, category, text_ko, text_en, answer_type, options, base_weight, effectiveness_score, can_be_dealbreaker, tags, placeholder, max_length) VALUES

-- CORE QUESTIONS (Q1-5) - Only disability_acceptance can be dealbreaker
('marriage_timeline', '결혼계획', '결혼은 언제쯤 생각하고 계세요?', 'When are you thinking about marriage?', 'choice', '[{"value": "within_1_year", "text_ko": "1년 이내에 하고 싶어요", "text_en": "Within 1 year", "match_weight": 1.0}, {"value": "1_2_years", "text_ko": "1-2년 정도 생각해요", "text_en": "1-2 years", "match_weight": 0.95}, {"value": "2_3_years", "text_ko": "2-3년 후에요", "text_en": "2-3 years", "match_weight": 0.85}, {"value": "3_5_years", "text_ko": "3년 이상 후에요", "text_en": "3+ years later", "match_weight": 0.7}, {"value": "not_decided", "text_ko": "아직 생각 중이에요", "text_en": "Still thinking", "match_weight": 0.5}]'::jsonb, 0.95, 10.0, false, ARRAY['결혼', '시기'], NULL, NULL),
('children_plan', '결혼계획', '결혼 후 자녀 계획은 어떻게 생각하세요?', 'What are your thoughts on having children?', 'choice', '[{"value": "want_2_3", "text_ko": "2-3명 갖고 싶어요", "text_en": "Would like 2-3", "match_weight": 1.0}, {"value": "want_1", "text_ko": "1명 갖고 싶어요", "text_en": "Would like 1", "match_weight": 0.85}, {"value": "undecided", "text_ko": "아직 생각 중이에요", "text_en": "Still thinking", "match_weight": 0.6}, {"value": "no_children", "text_ko": "자녀 없이 살고 싶어요", "text_en": "Prefer no children", "match_weight": 0.3}]'::jsonb, 0.95, 9.9, false, ARRAY['자녀'], NULL, NULL),
('disability_acceptance', '가치관', '신체적 차이가 있는 분과의 연애에 대해 어떻게 생각하시나요?', 'How do you feel about dating someone with physical differences?', 'choice', '[{"value": "fully_open", "text_ko": "전혀 문제없어요", "text_en": "Completely open", "match_weight": 1.0}, {"value": "depends", "text_ko": "상황에 따라 달라요", "text_en": "Depends on situation", "match_weight": 0.5}, {"value": "prefer_not", "text_ko": "조금 어려울 것 같아요", "text_en": "Might be challenging", "match_weight": 0.0}]'::jsonb, 0.90, 9.8, true, ARRAY['포용'], NULL, NULL),
('conflict_resolution', '갈등해결', '연인과 심하게 다투었을 때, 어떻게 해결하시나요?', 'How do you resolve serious disagreements with your partner?', 'choice', '[{"value": "calm_discussion", "text_ko": "마음을 진정시킨 후 대화해요", "text_en": "Calm down first, then talk", "match_weight": 1.0}, {"value": "immediate_talk", "text_ko": "바로 대화로 풀어요", "text_en": "Talk it out immediately", "match_weight": 0.95}, {"value": "need_time", "text_ko": "혼자 생각할 시간이 필요해요", "text_en": "Need time to think alone", "match_weight": 0.7}, {"value": "avoid", "text_ko": "갈등 상황을 피하는 편이에요", "text_en": "Tend to avoid conflict", "match_weight": 0.3}]'::jsonb, 0.95, 9.7, false, ARRAY['갈등'], NULL, NULL),
('trust_jealousy', '갈등해결', '연인이 이성 친구와 단둘이 만난다면 어떻게 느끼세요?', 'How would you feel if your partner met a friend of the opposite gender alone?', 'choice', '[{"value": "trust_fully", "text_ko": "전적으로 믿어요", "text_en": "Completely trust them", "match_weight": 1.0}, {"value": "express_feeling", "text_ko": "솔직하게 제 마음을 표현해요", "text_en": "Express my feelings honestly", "match_weight": 0.95}, {"value": "ask_details", "text_ko": "어떤 분인지 여쭤볼 것 같아요", "text_en": "Would ask about them", "match_weight": 0.85}, {"value": "feel_anxious", "text_ko": "조금 불안하지만 참을 것 같아요", "text_en": "A bit anxious but would endure", "match_weight": 0.5}, {"value": "cannot_accept", "text_ko": "솔직히 받아들이기 어려워요", "text_en": "Honestly difficult to accept", "match_weight": 0.2}]'::jsonb, 0.90, 9.5, false, ARRAY['신뢰'], NULL, NULL),

-- RELATIONSHIP DYNAMICS (Q6-15)
('emotional_support', '감정지원', '연인이 힘들어할 때 어떻게 해주시나요?', 'How do you support your partner when they are struggling?', 'choice', '[{"value": "listen_empathize", "text_ko": "공감하며 이야기를 들어줘요", "text_en": "Listen with empathy", "match_weight": 1.0}, {"value": "give_solution", "text_ko": "해결책을 함께 찾아봐요", "text_en": "Help find solutions", "match_weight": 0.8}, {"value": "cheer_up", "text_ko": "기분 전환을 도와줘요", "text_en": "Help cheer them up", "match_weight": 0.7}, {"value": "give_space", "text_ko": "혼자 생각할 시간을 줘요", "text_en": "Give them space", "match_weight": 0.6}]'::jsonb, 0.85, 9.0, false, ARRAY['감정'], NULL, NULL),
('communication_frequency', '소통', '연인과 얼마나 자주 연락하고 싶으세요?', 'How often would you like to communicate with your partner?', 'choice', '[{"value": "constant", "text_ko": "수시로 연락하고 싶어요", "text_en": "Constantly throughout the day", "match_weight": 1.0}, {"value": "daily_multiple", "text_ko": "하루에 여러 번이요", "text_en": "Several times a day", "match_weight": 0.9}, {"value": "daily_once", "text_ko": "하루에 한 번 정도요", "text_en": "About once a day", "match_weight": 0.7}, {"value": "few_week", "text_ko": "주 2-3회 정도면 충분해요", "text_en": "2-3 times a week is enough", "match_weight": 0.5}]'::jsonb, 0.80, 8.5, false, ARRAY['소통'], NULL, NULL),
('attachment_style', '애착', '연애할 때 어떤 스타일이세요?', 'What is your attachment style in relationships?', 'choice', '[{"value": "secure", "text_ko": "안정적이고 편안해요", "text_en": "Secure and comfortable", "match_weight": 1.0}, {"value": "anxious", "text_ko": "상대방 반응에 민감한 편이에요", "text_en": "Sensitive to partner's reactions", "match_weight": 0.7}, {"value": "avoidant", "text_ko": "어느 정도 거리감이 필요해요", "text_en": "Need some distance", "match_weight": 0.6}, {"value": "not_sure", "text_ko": "아직 잘 모르겠어요", "text_en": "Not sure yet", "match_weight": 0.5}]'::jsonb, 0.85, 8.8, false, ARRAY['애착'], NULL, NULL),
('love_language', '애정표현', '언제 가장 사랑받는다고 느끼세요?', 'When do you feel most loved?', 'choice', '[{"value": "words", "text_ko": "사랑한다는 말을 들을 때요", "text_en": "When I hear words of affirmation", "match_weight": 1.0}, {"value": "quality_time", "text_ko": "함께 시간을 보낼 때요", "text_en": "When we spend quality time together", "match_weight": 0.95}, {"value": "physical_touch", "text_ko": "스킨십을 할 때요", "text_en": "Through physical affection", "match_weight": 0.9}, {"value": "acts_service", "text_ko": "배려하는 행동을 받을 때요", "text_en": "When they do thoughtful things", "match_weight": 0.85}, {"value": "gifts", "text_ko": "선물을 받을 때요", "text_en": "When I receive gifts", "match_weight": 0.8}]'::jsonb, 0.80, 8.6, false, ARRAY['애정'], NULL, NULL),
('date_frequency', '데이트', '연인과 일주일에 몇 번 만나고 싶으세요?', 'How often would you like to see your partner per week?', 'choice', '[{"value": "everyday", "text_ko": "거의 매일 만나고 싶어요", "text_en": "Almost every day", "match_weight": 1.0}, {"value": "4_5_times", "text_ko": "주 4-5회 정도요", "text_en": "About 4-5 times", "match_weight": 0.9}, {"value": "2_3_times", "text_ko": "주 2-3회 정도요", "text_en": "About 2-3 times", "match_weight": 0.8}, {"value": "once_week", "text_ko": "주 1회 정도면 충분해요", "text_en": "Once a week is enough", "match_weight": 0.6}]'::jsonb, 0.75, 7.8, false, ARRAY['데이트'], NULL, NULL),
('anniversary_importance', '기념일', '기념일을 얼마나 중요하게 생각하세요?', 'How important are anniversaries to you?', 'choice', '[{"value": "very_important", "text_ko": "매우 중요해요, 꼭 챙겨요", "text_en": "Very important, always celebrate", "match_weight": 1.0}, {"value": "important", "text_ko": "중요해요, 챙기려고 노력해요", "text_en": "Important, try to celebrate", "match_weight": 0.9}, {"value": "moderate", "text_ko": "기억하면 챙겨요", "text_en": "Celebrate if I remember", "match_weight": 0.6}, {"value": "not_important", "text_ko": "크게 신경 쓰지 않아요", "text_en": "Don't focus on it much", "match_weight": 0.3}]'::jsonb, 0.70, 7.5, false, ARRAY['기념일'], NULL, NULL),
('future_planning', '미래', '미래 계획에 대해 의견이 다를 때 어떻게 하세요?', 'How do you handle disagreements about future plans?', 'choice', '[{"value": "thorough_discussion", "text_ko": "충분히 대화하며 토론해요", "text_en": "Discuss thoroughly together", "match_weight": 1.0}, {"value": "compromise", "text_ko": "서로 양보하며 조율해요", "text_en": "Compromise with each other", "match_weight": 0.95}, {"value": "practical_choice", "text_ko": "현실적인 선택을 해요", "text_en": "Make practical choices", "match_weight": 0.8}, {"value": "take_time", "text_ko": "천천히 시간을 두고 결정해요", "text_en": "Take time to decide", "match_weight": 0.75}]'::jsonb, 0.85, 8.7, false, ARRAY['미래'], NULL, NULL),
('personal_space', '독립성', '혼자만의 시간이 얼마나 필요하세요?', 'How much personal time do you need?', 'choice', '[{"value": "need_regular", "text_ko": "정기적으로 필요해요", "text_en": "Need it regularly", "match_weight": 1.0}, {"value": "sometimes", "text_ko": "가끔 필요해요", "text_en": "Sometimes need it", "match_weight": 0.8}, {"value": "rarely", "text_ko": "거의 필요하지 않아요", "text_en": "Rarely need it", "match_weight": 0.6}, {"value": "always_together", "text_ko": "항상 함께 있고 싶어요", "text_en": "Prefer always being together", "match_weight": 0.4}]'::jsonb, 0.75, 7.6, false, ARRAY['독립성'], NULL, NULL),
('social_life_balance', '사회생활', '친구들과 얼마나 자주 만나세요?', 'How often do you meet with friends?', 'choice', '[{"value": "weekly", "text_ko": "주 1회 이상 만나요", "text_en": "Once a week or more", "match_weight": 1.0}, {"value": "biweekly", "text_ko": "2주에 1회 정도요", "text_en": "About every two weeks", "match_weight": 0.9}, {"value": "monthly", "text_ko": "한 달에 1-2회 정도요", "text_en": "Once or twice a month", "match_weight": 0.7}, {"value": "rarely", "text_ko": "거의 안 만나는 편이에요", "text_en": "Rarely meet up", "match_weight": 0.5}]'::jsonb, 0.70, 7.2, false, ARRAY['사회생활'], NULL, NULL),
('physical_affection', '스킨십', '스킨십은 얼마나 중요하세요?', 'How important is physical affection to you?', 'choice', '[{"value": "very_important", "text_ko": "매우 중요해요", "text_en": "Very important", "match_weight": 1.0}, {"value": "important", "text_ko": "중요한 편이에요", "text_en": "Quite important", "match_weight": 0.9}, {"value": "moderate", "text_ko": "적당히 좋아요", "text_en": "Moderately important", "match_weight": 0.7}, {"value": "minimal", "text_ko": "최소한이면 충분해요", "text_en": "Minimal is enough", "match_weight": 0.4}]'::jsonb, 0.75, 7.9, false, ARRAY['스킨십'], NULL, NULL),

-- FAMILY & VALUES (Q16-25)
('parents_relationship', '가족', '부모님과의 관계는 어떠세요?', 'How is your relationship with your parents?', 'choice', '[{"value": "very_close", "text_ko": "매우 친밀해요", "text_en": "Very close", "match_weight": 1.0}, {"value": "close", "text_ko": "친밀한 편이에요", "text_en": "Quite close", "match_weight": 0.9}, {"value": "moderate", "text_ko": "보통이에요", "text_en": "Average", "match_weight": 0.7}, {"value": "distant", "text_ko": "약간 거리감이 있어요", "text_en": "Somewhat distant", "match_weight": 0.5}]'::jsonb, 0.80, 8.3, false, ARRAY['가족'], NULL, NULL),
('holiday_obligations', '명절', '명절에 양가 방문은 어떻게 생각하세요?', 'How do you feel about visiting both families during holidays?', 'choice', '[{"value": "visit_both", "text_ko": "양가 모두 방문하고 싶어요", "text_en": "Want to visit both", "match_weight": 1.0}, {"value": "alternate", "text_ko": "번갈아 방문하면 좋겠어요", "text_en": "Prefer alternating", "match_weight": 0.9}, {"value": "new_way", "text_ko": "새로운 방식을 만들고 싶어요", "text_en": "Want to create new traditions", "match_weight": 0.75}, {"value": "flexible", "text_ko": "상황에 따라 유연하게요", "text_en": "Flexible depending on situation", "match_weight": 0.5}]'::jsonb, 0.85, 8.6, false, ARRAY['명절'], NULL, NULL),
('financial_transparency', '재정', '결혼 후 가계 관리는 어떻게 하고 싶으세요?', 'How would you like to manage household finances after marriage?', 'choice', '[{"value": "fully_shared", "text_ko": "완전히 공동으로 관리해요", "text_en": "Fully shared management", "match_weight": 1.0}, {"value": "mostly_shared", "text_ko": "대부분 공동으로 해요", "text_en": "Mostly shared", "match_weight": 0.9}, {"value": "proportional", "text_ko": "수입 비율로 분담해요", "text_en": "Split by income ratio", "match_weight": 0.7}, {"value": "separate", "text_ko": "각자 관리하고 싶어요", "text_en": "Prefer separate management", "match_weight": 0.4}]'::jsonb, 0.85, 8.8, false, ARRAY['재정'], NULL, NULL),
('career_priority', '커리어', '일과 가정 중 우선순위는 어떻게 생각하세요?', 'How do you prioritize work and family?', 'choice', '[{"value": "family_first", "text_ko": "가정을 우선시해요", "text_en": "Family comes first", "match_weight": 1.0}, {"value": "balanced", "text_ko": "균형 있게 하고 싶어요", "text_en": "Want to balance both", "match_weight": 0.95}, {"value": "career_important", "text_ko": "커리어도 중요해요", "text_en": "Career is also important", "match_weight": 0.8}, {"value": "career_first", "text_ko": "커리어를 우선시해요", "text_en": "Career comes first", "match_weight": 0.6}]'::jsonb, 0.85, 8.7, false, ARRAY['커리어'], NULL, NULL),
('household_division', '가사', '가사 분담은 어떻게 하고 싶으세요?', 'How would you like to divide household chores?', 'choice', '[{"value": "equal_split", "text_ko": "동등하게 나누고 싶어요", "text_en": "Want to split equally", "match_weight": 1.0}, {"value": "flexible", "text_ko": "상황에 따라 유연하게요", "text_en": "Flexible based on situation", "match_weight": 0.9}, {"value": "by_strength", "text_ko": "각자 잘하는 것을 맡아요", "text_en": "Each does what they're good at", "match_weight": 0.8}, {"value": "hire_help", "text_ko": "도우미를 고용하고 싶어요", "text_en": "Would like to hire help", "match_weight": 0.7}]'::jsonb, 0.80, 8.4, false, ARRAY['가사'], NULL, NULL),
('religion_spirituality', '종교', '종교는 얼마나 중요하세요?', 'How important is religion to you?', 'choice', '[{"value": "very_important", "text_ko": "매우 중요해요", "text_en": "Very important", "match_weight": 1.0}, {"value": "somewhat", "text_ko": "어느 정도 중요해요", "text_en": "Somewhat important", "match_weight": 0.7}, {"value": "not_important", "text_ko": "크게 중요하지 않아요", "text_en": "Not very important", "match_weight": 0.3}, {"value": "respect_all", "text_ko": "모든 종교를 존중해요", "text_en": "Respect all religions", "match_weight": 0.8}]'::jsonb, 0.75, 7.8, false, ARRAY['종교'], NULL, NULL),
('political_views', '정치', '정치에 대한 생각은 어떠세요?', 'What are your thoughts on politics?', 'choice', '[{"value": "progressive", "text_ko": "진보적인 편이에요", "text_en": "Tend to be progressive", "match_weight": 1.0}, {"value": "moderate", "text_ko": "중도적이에요", "text_en": "Moderate", "match_weight": 0.8}, {"value": "conservative", "text_ko": "보수적인 편이에요", "text_en": "Tend to be conservative", "match_weight": 0.6}, {"value": "not_interested", "text_ko": "크게 관심 없어요", "text_en": "Not very interested", "match_weight": 0.5}]'::jsonb, 0.70, 7.3, false, ARRAY['정치'], NULL, NULL),
('environmental_values', '환경', '환경보호에 얼마나 관심이 있으세요?', 'How concerned are you about the environment?', 'choice', '[{"value": "very_active", "text_ko": "적극적으로 실천해요", "text_en": "Actively practice", "match_weight": 1.0}, {"value": "try_best", "text_ko": "노력하는 편이에요", "text_en": "Try my best", "match_weight": 0.9}, {"value": "basic_only", "text_ko": "기본적인 것만 해요", "text_en": "Do the basics", "match_weight": 0.6}, {"value": "not_priority", "text_ko": "크게 신경 쓰지 않아요", "text_en": "Don't focus on it much", "match_weight": 0.3}]'::jsonb, 0.65, 6.8, false, ARRAY['환경'], NULL, NULL),
('life_goals', '목표', '인생에서 가장 중요한 목표는 무엇인가요?', 'What is your most important life goal?', 'choice', '[{"value": "family_happiness", "text_ko": "가정의 행복이에요", "text_en": "Family happiness", "match_weight": 1.0}, {"value": "career_success", "text_ko": "커리어 성공이에요", "text_en": "Career success", "match_weight": 0.8}, {"value": "personal_growth", "text_ko": "개인적인 성장이에요", "text_en": "Personal growth", "match_weight": 0.85}, {"value": "financial_stability", "text_ko": "경제적 안정이에요", "text_en": "Financial stability", "match_weight": 0.9}, {"value": "social_contribution", "text_ko": "사회에 기여하는 것이에요", "text_en": "Contributing to society", "match_weight": 0.75}]'::jsonb, 0.80, 8.2, false, ARRAY['목표'], NULL, NULL),
('money_attitude', '금전관', '돈에 대한 태도는 어떠세요?', 'What is your attitude toward money?', 'choice', '[{"value": "save_invest", "text_ko": "저축과 투자를 중시해요", "text_en": "Focus on saving and investing", "match_weight": 1.0}, {"value": "balanced", "text_ko": "균형 있게 사용해요", "text_en": "Use money in a balanced way", "match_weight": 0.9}, {"value": "enjoy_present", "text_ko": "현재를 즐기는 편이에요", "text_en": "Prefer enjoying the present", "match_weight": 0.7}, {"value": "not_focused", "text_ko": "크게 신경 쓰지 않아요", "text_en": "Don't focus on it much", "match_weight": 0.4}]'::jsonb, 0.85, 8.5, false, ARRAY['금전'], NULL, NULL),

-- LIFESTYLE (Q26-35)
('living_location', '주거', '어디에서 살고 싶으세요?', 'Where would you like to live?', 'choice', '[{"value": "city_center", "text_ko": "도심이 좋아요", "text_en": "Prefer city center", "match_weight": 1.0}, {"value": "suburb", "text_ko": "교외가 좋아요", "text_en": "Prefer suburbs", "match_weight": 0.8}, {"value": "countryside", "text_ko": "시골이 좋아요", "text_en": "Prefer countryside", "match_weight": 0.6}, {"value": "flexible", "text_ko": "어디든 괜찮아요", "text_en": "Anywhere is fine", "match_weight": 0.9}]'::jsonb, 0.75, 7.7, false, ARRAY['주거'], NULL, NULL),
('pet_preference', '반려동물', '반려동물에 대해 어떻게 생각하세요?', 'How do you feel about pets?', 'choice', '[{"value": "love_pets", "text_ko": "좋아해요, 키우고 싶어요", "text_en": "Love them, want to have pets", "match_weight": 1.0}, {"value": "okay_with", "text_ko": "괜찮아요", "text_en": "Fine with them", "match_weight": 0.8}, {"value": "prefer_not", "text_ko": "선호하지 않아요", "text_en": "Prefer not to have", "match_weight": 0.4}, {"value": "allergic", "text_ko": "알러지가 있어요", "text_en": "Have allergies", "match_weight": 0.2}]'::jsonb, 0.70, 7.1, false, ARRAY['반려동물'], NULL, NULL),
('exercise_habits', '운동', '운동은 얼마나 자주 하세요?', 'How often do you exercise?', 'choice', '[{"value": "daily", "text_ko": "거의 매일 해요", "text_en": "Almost daily", "match_weight": 1.0}, {"value": "regular", "text_ko": "주 3-4회 정도요", "text_en": "3-4 times a week", "match_weight": 0.9}, {"value": "sometimes", "text_ko": "가끔 해요", "text_en": "Sometimes", "match_weight": 0.6}, {"value": "rarely", "text_ko": "거의 안 하는 편이에요", "text_en": "Rarely exercise", "match_weight": 0.3}]'::jsonb, 0.65, 6.9, false, ARRAY['운동'], NULL, NULL),
('drinking_habits', '음주', '술은 얼마나 자주 드세요?', 'How often do you drink alcohol?', 'choice', '[{"value": "never", "text_ko": "마시지 않아요", "text_en": "Don't drink", "match_weight": 1.0}, {"value": "social", "text_ko": "사교적으로만 마셔요", "text_en": "Only socially", "match_weight": 0.9}, {"value": "weekly", "text_ko": "주 1-2회 정도요", "text_en": "1-2 times a week", "match_weight": 0.7}, {"value": "frequent", "text_ko": "자주 마시는 편이에요", "text_en": "Drink frequently", "match_weight": 0.4}]'::jsonb, 0.80, 8.0, false, ARRAY['음주'], NULL, NULL),
('smoking_status', '흡연', '흡연은 하세요?', 'Do you smoke?', 'choice', '[{"value": "non_smoker", "text_ko": "피우지 않아요", "text_en": "Don't smoke", "match_weight": 1.0}, {"value": "quit", "text_ko": "금연했어요", "text_en": "Quit smoking", "match_weight": 0.85}, {"value": "occasional", "text_ko": "가끔 피워요", "text_en": "Occasionally", "match_weight": 0.5}, {"value": "regular", "text_ko": "피우는 편이에요", "text_en": "Smoke regularly", "match_weight": 0.2}]'::jsonb, 0.85, 8.3, false, ARRAY['흡연'], NULL, NULL),
('travel_preference', '여행', '여행 스타일은 어떠세요?', 'What is your travel style?', 'choice', '[{"value": "adventure", "text_ko": "모험적인 여행을 좋아해요", "text_en": "Love adventurous trips", "match_weight": 1.0}, {"value": "cultural", "text_ko": "문화 탐방을 좋아해요", "text_en": "Enjoy cultural exploration", "match_weight": 0.9}, {"value": "relaxation", "text_ko": "휴양 위주로 좋아해요", "text_en": "Prefer relaxing trips", "match_weight": 0.8}, {"value": "not_interested", "text_ko": "여행을 별로 좋아하지 않아요", "text_en": "Not really into traveling", "match_weight": 0.4}]'::jsonb, 0.70, 7.4, false, ARRAY['여행'], NULL, NULL),
('food_preference', '음식', '음식 취향은 어떠세요?', 'What are your food preferences?', 'choice', '[{"value": "adventurous", "text_ko": "다양한 음식에 도전해요", "text_en": "Try diverse foods", "match_weight": 1.0}, {"value": "open_minded", "text_ko": "열린 마음으로 먹어요", "text_en": "Open to trying new things", "match_weight": 0.9}, {"value": "selective", "text_ko": "좋아하는 것 위주로 먹어요", "text_en": "Prefer what I like", "match_weight": 0.6}, {"value": "picky", "text_ko": "조금 까다로운 편이에요", "text_en": "A bit picky", "match_weight": 0.4}]'::jsonb, 0.65, 6.7, false, ARRAY['음식'], NULL, NULL),
('sleep_schedule', '수면', '수면 패턴은 어떠세요?', 'What is your sleep pattern?', 'choice', '[{"value": "early_bird", "text_ko": "아침형 인간이에요", "text_en": "I'm an early bird", "match_weight": 1.0}, {"value": "moderate", "text_ko": "보통이에요", "text_en": "Average schedule", "match_weight": 0.8}, {"value": "night_owl", "text_ko": "저녁형 인간이에요", "text_en": "I'm a night owl", "match_weight": 0.6}, {"value": "irregular", "text_ko": "불규칙한 편이에요", "text_en": "Irregular schedule", "match_weight": 0.5}]'::jsonb, 0.70, 7.0, false, ARRAY['수면'], NULL, NULL),
('cleanliness', '청결', '청결에 대한 기준은 어떠세요?', 'What are your cleanliness standards?', 'choice', '[{"value": "very_clean", "text_ko": "매우 깔끔해야 해요", "text_en": "Need it very clean", "match_weight": 1.0}, {"value": "clean", "text_ko": "깔끔한 편이에요", "text_en": "Prefer it clean", "match_weight": 0.9}, {"value": "moderate", "text_ko": "보통이에요", "text_en": "Average standards", "match_weight": 0.7}, {"value": "relaxed", "text_ko": "여유로운 편이에요", "text_en": "Pretty relaxed about it", "match_weight": 0.5}]'::jsonb, 0.75, 7.6, false, ARRAY['청결'], NULL, NULL),
('introvert_extrovert', '성격', '성격 유형은 어떠세요?', 'What is your personality type?', 'choice', '[{"value": "extrovert", "text_ko": "외향적인 편이에요", "text_en": "More extroverted", "match_weight": 1.0}, {"value": "ambivert", "text_ko": "상황에 따라 달라요", "text_en": "Depends on the situation", "match_weight": 0.9}, {"value": "introvert", "text_ko": "내향적인 편이에요", "text_en": "More introverted", "match_weight": 0.7}]'::jsonb, 0.75, 7.8, false, ARRAY['성격'], NULL, NULL),

-- TEXT QUESTIONS (Q36-40)
('personal_values_lifestyle', '가치관', '당신의 일상과 삶에서 가장 중요하게 생각하는 가치는 무엇이며, 어떻게 실천하고 계신가요?', 'What values are most important in your daily life and how do you practice them?', 'text', '[]'::jsonb, 0.95, 9.9, false, ARRAY['가치관', '일상'], '예: 성실함을 중요하게 여겨 매일 아침 운동하고, 가족과의 시간을 우선시하며...', 400),
('ideal_relationship_dynamic', '연애관', '이상적인 연애 관계는 어떤 모습이라고 생각하시나요? 두 사람이 어떻게 함께 성장하길 바라시나요?', 'What does an ideal romantic relationship look like to you?', 'text', '[]'::jsonb, 0.95, 9.8, false, ARRAY['연애', '관계'], '예: 서로의 꿈을 응원하면서도 함께하는 시간을 소중히 여기고...', 350),
('future_life_vision', '미래', '5년 후, 10년 후 당신의 삶은 어떤 모습일까요? 파트너와 함께 이루고 싶은 것은?', 'What will your life look like in 5-10 years?', 'text', '[]'::jsonb, 0.90, 9.6, false, ARRAY['미래', '비전'], '예: 안정적인 직장에서 일하며 아이 둘과 함께 교외에 집을 마련하고...', 350),
('conflict_growth_philosophy', '성장', '관계에서 어려움이나 갈등이 생겼을 때, 어떻게 극복하고 성장해왔나요?', 'How have you overcome difficulties in relationships?', 'text', '[]'::jsonb, 0.90, 9.4, false, ARRAY['갈등', '성장'], '예: 과거엔 감정을 숨겼지만, 이제는 솔직하게 표현하고...', 350),
('life_philosophy_happiness', '행복', '당신에게 행복한 삶이란 무엇이며, 어떤 순간에 가장 만족감을 느끼시나요?', 'What is a happy life to you?', 'text', '[]'::jsonb, 0.85, 9.1, false, ARRAY['행복', '만족'], '예: 사랑하는 사람들과 함께 웃으며 식사할 때, 작은 목표를 이뤘을 때...', 300);

INSERT INTO question_performance (question_id)
SELECT id FROM questions
ON CONFLICT (question_id) DO NOTHING;
