-- ==========================================
-- FLIO Complete 40-Question Database
-- Research-based: Gottman Institute, Attachment Theory, Big Five, Korean marriage agencies (듀오, 가연)
-- ==========================================

CREATE TABLE IF NOT EXISTS questions (
    id VARCHAR(100) PRIMARY KEY,
    category VARCHAR(50) NOT NULL,
    text_ko TEXT NOT NULL,
    text_en TEXT NOT NULL,
    answer_type VARCHAR(50) NOT NULL,
    options JSONB NOT NULL,
    base_weight FLOAT DEFAULT 0.5,
    effectiveness_score FLOAT DEFAULT 5.0,
    can_be_dealbreaker BOOLEAN DEFAULT false,
    tags TEXT[],
    placeholder TEXT,
    max_length INTEGER,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_questions_category ON questions(category);
CREATE INDEX IF NOT EXISTS idx_questions_effectiveness ON questions(effectiveness_score DESC);
CREATE INDEX IF NOT EXISTS idx_questions_active ON questions(is_active) WHERE is_active = TRUE;

CREATE TABLE IF NOT EXISTS question_performance (
    question_id VARCHAR(100) PRIMARY KEY REFERENCES questions(id) ON DELETE CASCADE,
    total_answers INTEGER DEFAULT 0,
    avg_importance FLOAT DEFAULT 0.0,
    dealbreaker_count INTEGER DEFAULT 0,
    last_answered_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

INSERT INTO questions (id, category, text_ko, text_en, answer_type, options, base_weight, effectiveness_score, can_be_dealbreaker, tags, placeholder, max_length) VALUES

-- DEALBREAKERS (Q1-5)
('marriage_timeline', '결혼계획', '결혼은 언제쯤 생각하고 계세요?', 'When are you thinking about marriage?', 'choice', '[{"value": "within_1_year", "text_ko": "1년 이내", "text_en": "Within 1 year", "match_weight": 1.0}, {"value": "1_2_years", "text_ko": "1-2년 이내", "text_en": "1-2 years", "match_weight": 0.95}, {"value": "2_3_years", "text_ko": "2-3년 이내", "text_en": "2-3 years", "match_weight": 0.85}, {"value": "3_5_years", "text_ko": "3-5년 이후", "text_en": "3-5 years later", "match_weight": 0.7}, {"value": "not_decided", "text_ko": "아직 결정 못함", "text_en": "Not decided yet", "match_weight": 0.5}]'::jsonb, 0.95, 10.0, true, ARRAY['결혼', '시기'], NULL, NULL),
('children_plan', '결혼계획', '결혼 후 자녀 계획은?', 'Plans for children?', 'choice', '[{"value": "want_2_3", "text_ko": "2-3명 원함", "text_en": "Want 2-3", "match_weight": 1.0}, {"value": "want_1", "text_ko": "1명 원함", "text_en": "Want 1", "match_weight": 0.85}, {"value": "undecided", "text_ko": "미정", "text_en": "Undecided", "match_weight": 0.6}, {"value": "no_children", "text_ko": "자녀 없이", "text_en": "No children", "match_weight": 0.3}]'::jsonb, 0.95, 9.9, true, ARRAY['자녀'], NULL, NULL),
('disability_acceptance', '가치관', '장애가 있는 분과 연애/결혼은?', 'Dating someone with disability?', 'choice', '[{"value": "fully_open", "text_ko": "전혀 문제없음", "text_en": "No problem", "match_weight": 1.0}, {"value": "depends", "text_ko": "정도에 따라", "text_en": "Depends", "match_weight": 0.5}, {"value": "difficult", "text_ko": "어려울 듯", "text_en": "Difficult", "match_weight": 0.0}]'::jsonb, 0.90, 9.8, true, ARRAY['포용'], NULL, NULL),
('conflict_resolution', '갈등해결', '심한 다툼 시 대처법은?', 'How handle serious fights?', 'choice', '[{"value": "calm_discussion", "text_ko": "진정 후 대화", "text_en": "Calm then talk", "match_weight": 1.0}, {"value": "immediate_talk", "text_ko": "즉시 대화", "text_en": "Talk immediately", "match_weight": 0.95}, {"value": "need_time", "text_ko": "혼자 시간 필요", "text_en": "Need time alone", "match_weight": 0.7}, {"value": "avoid", "text_ko": "갈등 피함", "text_en": "Avoid conflict", "match_weight": 0.3}]'::jsonb, 0.95, 9.7, true, ARRAY['갈등'], NULL, NULL),
('trust_jealousy', '갈등해결', '연인이 이성친구와 단둘이 만나면?', 'Partner meets opposite gender alone?', 'choice', '[{"value": "trust_fully", "text_ko": "믿고 OK", "text_en": "Trust fully", "match_weight": 1.0}, {"value": "express_feeling", "text_ko": "불편함 표현", "text_en": "Express discomfort", "match_weight": 0.95}, {"value": "ask_details", "text_ko": "누군지 물어봄", "text_en": "Ask who", "match_weight": 0.85}, {"value": "feel_anxious", "text_ko": "불안하지만 참음", "text_en": "Anxious but endure", "match_weight": 0.5}, {"value": "cannot_accept", "text_ko": "받아들이기 어려움", "text_en": "Cannot accept", "match_weight": 0.2}]'::jsonb, 0.90, 9.5, true, ARRAY['신뢰'], NULL, NULL),

-- RELATIONSHIP DYNAMICS (Q6-15)
('emotional_support', '감정지원', '연인이 힘들 때 반응은?', 'When partner struggles?', 'choice', '[{"value": "listen_empathize", "text_ko": "공감하며 들어줌", "text_en": "Listen with empathy", "match_weight": 1.0}, {"value": "give_solution", "text_ko": "해결책 제시", "text_en": "Offer solutions", "match_weight": 0.8}, {"value": "cheer_up", "text_ko": "기분 전환", "text_en": "Cheer up", "match_weight": 0.7}, {"value": "give_space", "text_ko": "혼자 있게", "text_en": "Give space", "match_weight": 0.6}]'::jsonb, 0.85, 9.0, false, ARRAY['감정'], NULL, NULL),
('communication_frequency', '소통', '연락 빈도는?', 'Communication frequency?', 'choice', '[{"value": "constant", "text_ko": "수시로", "text_en": "Constant", "match_weight": 1.0}, {"value": "daily_multiple", "text_ko": "하루 여러번", "text_en": "Multiple daily", "match_weight": 0.9}, {"value": "daily_once", "text_ko": "하루 한번", "text_en": "Once daily", "match_weight": 0.7}, {"value": "few_week", "text_ko": "주 2-3회", "text_en": "2-3/week", "match_weight": 0.5}]'::jsonb, 0.80, 8.5, false, ARRAY['소통'], NULL, NULL),
('attachment_style', '애착', '연애 스타일은?', 'Attachment style?', 'choice', '[{"value": "secure", "text_ko": "안정형", "text_en": "Secure", "match_weight": 1.0}, {"value": "anxious", "text_ko": "불안형", "text_en": "Anxious", "match_weight": 0.7}, {"value": "avoidant", "text_ko": "회피형", "text_en": "Avoidant", "match_weight": 0.6}, {"value": "not_sure", "text_ko": "모르겠음", "text_en": "Not sure", "match_weight": 0.5}]'::jsonb, 0.85, 8.8, false, ARRAY['애착'], NULL, NULL),
('love_language', '애정표현', '가장 사랑받는다 느낄 때는?', 'When feel most loved?', 'choice', '[{"value": "words", "text_ko": "사랑한다는 말", "text_en": "Words", "match_weight": 1.0}, {"value": "quality_time", "text_ko": "함께하는 시간", "text_en": "Quality time", "match_weight": 0.95}, {"value": "physical_touch", "text_ko": "스킨십", "text_en": "Physical touch", "match_weight": 0.9}, {"value": "acts_service", "text_ko": "배려 행동", "text_en": "Acts of service", "match_weight": 0.85}, {"value": "gifts", "text_ko": "선물", "text_en": "Gifts", "match_weight": 0.8}]'::jsonb, 0.80, 8.6, false, ARRAY['애정'], NULL, NULL),
('date_frequency', '데이트', '주 몇회 만나는게 적당?', 'How often meet per week?', 'choice', '[{"value": "everyday", "text_ko": "거의 매일", "text_en": "Almost everyday", "match_weight": 1.0}, {"value": "4_5_times", "text_ko": "주 4-5회", "text_en": "4-5 times", "match_weight": 0.9}, {"value": "2_3_times", "text_ko": "주 2-3회", "text_en": "2-3 times", "match_weight": 0.8}, {"value": "once_week", "text_ko": "주 1회", "text_en": "Once", "match_weight": 0.6}]'::jsonb, 0.75, 7.8, false, ARRAY['데이트'], NULL, NULL),
('anniversary_importance', '기념일', '기념일 챙기는 정도는?', 'Anniversary importance?', 'choice', '[{"value": "very_important", "text_ko": "매우 중요, 꼭 챙김", "text_en": "Very important", "match_weight": 1.0}, {"value": "important", "text_ko": "중요, 챙기려 노력", "text_en": "Important", "match_weight": 0.9}, {"value": "moderate", "text_ko": "기억하면 챙김", "text_en": "If remember", "match_weight": 0.6}, {"value": "not_important", "text_ko": "별로 안중요", "text_en": "Not important", "match_weight": 0.3}]'::jsonb, 0.70, 7.5, false, ARRAY['기념일'], NULL, NULL),
('future_planning', '미래', '미래 계획 의견 차이시?', 'When disagree on future?', 'choice', '[{"value": "thorough_discussion", "text_ko": "충분히 토론", "text_en": "Thorough discussion", "match_weight": 1.0}, {"value": "compromise", "text_ko": "서로 양보", "text_en": "Compromise", "match_weight": 0.95}, {"value": "practical_choice", "text_ko": "현실적인 쪽", "text_en": "Practical choice", "match_weight": 0.8}, {"value": "take_time", "text_ko": "천천히 결정", "text_en": "Take time", "match_weight": 0.75}]'::jsonb, 0.85, 8.7, false, ARRAY['미래'], NULL, NULL),
('personal_space', '독립성', '개인 시간 필요성은?', 'Need for personal space?', 'choice', '[{"value": "need_regular", "text_ko": "정기적으로 필요", "text_en": "Need regularly", "match_weight": 1.0}, {"value": "sometimes", "text_ko": "가끔 필요", "text_en": "Sometimes", "match_weight": 0.8}, {"value": "rarely", "text_ko": "거의 불필요", "text_en": "Rarely", "match_weight": 0.6}, {"value": "always_together", "text_ko": "항상 함께 선호", "text_en": "Always together", "match_weight": 0.4}]'::jsonb, 0.75, 7.6, false, ARRAY['독립성'], NULL, NULL),
('social_life_balance', '사회생활', '친구 모임 빈도는?', 'Friend gathering frequency?', 'choice', '[{"value": "weekly", "text_ko": "주 1회 이상", "text_en": "Weekly+", "match_weight": 1.0}, {"value": "biweekly", "text_ko": "2주 1회", "text_en": "Biweekly", "match_weight": 0.9}, {"value": "monthly", "text_ko": "월 1-2회", "text_en": "Monthly", "match_weight": 0.7}, {"value": "rarely", "text_ko": "거의 안만남", "text_en": "Rarely", "match_weight": 0.5}]'::jsonb, 0.70, 7.2, false, ARRAY['사회생활'], NULL, NULL),
('physical_affection', '스킨십', '스킨십 선호도는?', 'Physical affection preference?', 'choice', '[{"value": "very_important", "text_ko": "매우 중요", "text_en": "Very important", "match_weight": 1.0}, {"value": "important", "text_ko": "중요함", "text_en": "Important", "match_weight": 0.9}, {"value": "moderate", "text_ko": "적당히", "text_en": "Moderate", "match_weight": 0.7}, {"value": "minimal", "text_ko": "최소한만", "text_en": "Minimal", "match_weight": 0.4}]'::jsonb, 0.75, 7.9, false, ARRAY['스킨십'], NULL, NULL),

-- FAMILY & VALUES (Q16-25)
('parents_relationship', '가족', '부모님과 관계는?', 'Relationship with parents?', 'choice', '[{"value": "very_close", "text_ko": "매우 친밀", "text_en": "Very close", "match_weight": 1.0}, {"value": "close", "text_ko": "친밀함", "text_en": "Close", "match_weight": 0.9}, {"value": "moderate", "text_ko": "보통", "text_en": "Moderate", "match_weight": 0.7}, {"value": "distant", "text_ko": "거리감 있음", "text_en": "Distant", "match_weight": 0.5}]'::jsonb, 0.80, 8.3, false, ARRAY['가족'], NULL, NULL),
('holiday_obligations', '명절', '명절 양가 방문은?', 'Holiday family visits?', 'choice', '[{"value": "visit_both", "text_ko": "양가 모두 방문", "text_en": "Visit both", "match_weight": 1.0}, {"value": "alternate", "text_ko": "번갈아 방문", "text_en": "Alternate", "match_weight": 0.9}, {"value": "new_way", "text_ko": "새로운 방식", "text_en": "New way", "match_weight": 0.75}, {"value": "one_side", "text_ko": "한쪽만", "text_en": "One side", "match_weight": 0.5}]'::jsonb, 0.85, 8.6, false, ARRAY['명절'], NULL, NULL),
('financial_transparency', '재정', '가계 관리는?', 'Household finances?', 'choice', '[{"value": "fully_shared", "text_ko": "완전 공동", "text_en": "Fully shared", "match_weight": 1.0}, {"value": "mostly_shared", "text_ko": "대부분 공동", "text_en": "Mostly shared", "match_weight": 0.9}, {"value": "proportional", "text_ko": "비율로 분담", "text_en": "Proportional", "match_weight": 0.7}, {"value": "separate", "text_ko": "각자 관리", "text_en": "Separate", "match_weight": 0.4}]'::jsonb, 0.85, 8.8, false, ARRAY['재정'], NULL, NULL),
('career_priority', '커리어', '일과 가정 우선순위는?', 'Work vs family priority?', 'choice', '[{"value": "family_first", "text_ko": "가정 우선", "text_en": "Family first", "match_weight": 1.0}, {"value": "balanced", "text_ko": "균형있게", "text_en": "Balanced", "match_weight": 0.95}, {"value": "career_important", "text_ko": "커리어도 중요", "text_en": "Career important", "match_weight": 0.8}, {"value": "career_first", "text_ko": "커리어 우선", "text_en": "Career first", "match_weight": 0.6}]'::jsonb, 0.85, 8.7, false, ARRAY['커리어'], NULL, NULL),
('household_division', '가사', '가사 분담은?', 'Household chores division?', 'choice', '[{"value": "equal_split", "text_ko": "완전 평등 분담", "text_en": "Equal split", "match_weight": 1.0}, {"value": "flexible", "text_ko": "유연하게", "text_en": "Flexible", "match_weight": 0.9}, {"value": "traditional", "text_ko": "전통적 역할", "text_en": "Traditional", "match_weight": 0.6}, {"value": "hire_help", "text_ko": "도움 고용", "text_en": "Hire help", "match_weight": 0.7}]'::jsonb, 0.80, 8.4, false, ARRAY['가사'], NULL, NULL),
('religion_spirituality', '종교', '종교 중요도는?', 'Religion importance?', 'choice', '[{"value": "very_important", "text_ko": "매우 중요", "text_en": "Very important", "match_weight": 1.0}, {"value": "somewhat", "text_ko": "어느정도", "text_en": "Somewhat", "match_weight": 0.7}, {"value": "not_important", "text_ko": "중요하지 않음", "text_en": "Not important", "match_weight": 0.3}, {"value": "respect_all", "text_ko": "모든 종교 존중", "text_en": "Respect all", "match_weight": 0.8}]'::jsonb, 0.75, 7.8, false, ARRAY['종교'], NULL, NULL),
('political_views', '정치', '정치 성향은?', 'Political views?', 'choice', '[{"value": "progressive", "text_ko": "진보적", "text_en": "Progressive", "match_weight": 1.0}, {"value": "moderate", "text_ko": "중도", "text_en": "Moderate", "match_weight": 0.8}, {"value": "conservative", "text_ko": "보수적", "text_en": "Conservative", "match_weight": 0.6}, {"value": "not_interested", "text_ko": "관심없음", "text_en": "Not interested", "match_weight": 0.5}]'::jsonb, 0.70, 7.3, false, ARRAY['정치'], NULL, NULL),
('environmental_values', '환경', '환경보호 관심도는?', 'Environmental concern?', 'choice', '[{"value": "very_active", "text_ko": "적극 실천", "text_en": "Very active", "match_weight": 1.0}, {"value": "try_best", "text_ko": "노력함", "text_en": "Try my best", "match_weight": 0.9}, {"value": "basic_only", "text_ko": "기본만", "text_en": "Basic only", "match_weight": 0.6}, {"value": "not_priority", "text_ko": "우선순위 아님", "text_en": "Not priority", "match_weight": 0.3}]'::jsonb, 0.65, 6.8, false, ARRAY['환경'], NULL, NULL),
('life_goals', '목표', '인생 목표는?', 'Life goals?', 'choice', '[{"value": "family_happiness", "text_ko": "가정의 행복", "text_en": "Family happiness", "match_weight": 1.0}, {"value": "career_success", "text_ko": "커리어 성공", "text_en": "Career success", "match_weight": 0.8}, {"value": "personal_growth", "text_ko": "개인 성장", "text_en": "Personal growth", "match_weight": 0.85}, {"value": "financial_stability", "text_ko": "경제적 안정", "text_en": "Financial stability", "match_weight": 0.9}, {"value": "social_contribution", "text_ko": "사회 기여", "text_en": "Social contribution", "match_weight": 0.75}]'::jsonb, 0.80, 8.2, false, ARRAY['목표'], NULL, NULL),
('money_attitude', '금전관', '돈에 대한 태도는?', 'Attitude toward money?', 'choice', '[{"value": "save_invest", "text_ko": "저축/투자 중시", "text_en": "Save/invest", "match_weight": 1.0}, {"value": "balanced", "text_ko": "균형있게", "text_en": "Balanced", "match_weight": 0.9}, {"value": "enjoy_present", "text_ko": "현재 즐김", "text_en": "Enjoy present", "match_weight": 0.7}, {"value": "not_important", "text_ko": "별로 중요하지 않음", "text_en": "Not important", "match_weight": 0.4}]'::jsonb, 0.85, 8.5, false, ARRAY['금전'], NULL, NULL),

-- LIFESTYLE (Q26-35)
('living_location', '주거', '선호 거주지는?', 'Preferred living location?', 'choice', '[{"value": "city_center", "text_ko": "도심", "text_en": "City center", "match_weight": 1.0}, {"value": "suburb", "text_ko": "교외", "text_en": "Suburb", "match_weight": 0.8}, {"value": "countryside", "text_ko": "시골", "text_en": "Countryside", "match_weight": 0.6}, {"value": "flexible", "text_ko": "어디든 OK", "text_en": "Flexible", "match_weight": 0.9}]'::jsonb, 0.75, 7.7, false, ARRAY['주거'], NULL, NULL),
('pet_preference', '반려동물', '반려동물은?', 'Pets?', 'choice', '[{"value": "love_pets", "text_ko": "좋아함, 키우고 싶음", "text_en": "Love, want pets", "match_weight": 1.0}, {"value": "okay_with", "text_ko": "괜찮음", "text_en": "Okay with", "match_weight": 0.8}, {"value": "prefer_not", "text_ko": "선호 안함", "text_en": "Prefer not", "match_weight": 0.4}, {"value": "allergic", "text_ko": "알러지 있음", "text_en": "Allergic", "match_weight": 0.2}]'::jsonb, 0.70, 7.1, false, ARRAY['반려동물'], NULL, NULL),
('exercise_habits', '운동', '운동 빈도는?', 'Exercise frequency?', 'choice', '[{"value": "daily", "text_ko": "거의 매일", "text_en": "Daily", "match_weight": 1.0}, {"value": "regular", "text_ko": "주 3-4회", "text_en": "3-4 times/week", "match_weight": 0.9}, {"value": "sometimes", "text_ko": "가끔", "text_en": "Sometimes", "match_weight": 0.6}, {"value": "rarely", "text_ko": "거의 안함", "text_en": "Rarely", "match_weight": 0.3}]'::jsonb, 0.65, 6.9, false, ARRAY['운동'], NULL, NULL),
('drinking_habits', '음주', '음주 빈도는?', 'Drinking frequency?', 'choice', '[{"value": "never", "text_ko": "안마심", "text_en": "Never", "match_weight": 1.0}, {"value": "social", "text_ko": "사교적으로", "text_en": "Social", "match_weight": 0.9}, {"value": "weekly", "text_ko": "주 1-2회", "text_en": "1-2/week", "match_weight": 0.7}, {"value": "frequent", "text_ko": "자주", "text_en": "Frequent", "match_weight": 0.4}]'::jsonb, 0.80, 8.0, false, ARRAY['음주'], NULL, NULL),
('smoking_status', '흡연', '흡연 여부는?', 'Smoking status?', 'choice', '[{"value": "non_smoker", "text_ko": "비흡연", "text_en": "Non-smoker", "match_weight": 1.0}, {"value": "quit", "text_ko": "금연함", "text_en": "Quit", "match_weight": 0.85}, {"value": "occasional", "text_ko": "가끔", "text_en": "Occasional", "match_weight": 0.5}, {"value": "regular", "text_ko": "흡연", "text_en": "Regular", "match_weight": 0.2}]'::jsonb, 0.85, 8.3, false, ARRAY['흡연'], NULL, NULL),
('travel_preference', '여행', '여행 스타일은?', 'Travel style?', 'choice', '[{"value": "adventure", "text_ko": "모험적", "text_en": "Adventure", "match_weight": 1.0}, {"value": "cultural", "text_ko": "문화탐방", "text_en": "Cultural", "match_weight": 0.9}, {"value": "relaxation", "text_ko": "휴양", "text_en": "Relaxation", "match_weight": 0.8}, {"value": "not_interested", "text_ko": "별로 안좋아함", "text_en": "Not interested", "match_weight": 0.4}]'::jsonb, 0.70, 7.4, false, ARRAY['여행'], NULL, NULL),
('food_preference', '음식', '음식 취향은?', 'Food preference?', 'choice', '[{"value": "adventurous", "text_ko": "다양하게 도전", "text_en": "Adventurous", "match_weight": 1.0}, {"value": "open_minded", "text_ko": "열린 마음", "text_en": "Open-minded", "match_weight": 0.9}, {"value": "selective", "text_ko": "선택적", "text_en": "Selective", "match_weight": 0.6}, {"value": "picky", "text_ko": "까다로움", "text_en": "Picky", "match_weight": 0.4}]'::jsonb, 0.65, 6.7, false, ARRAY['음식'], NULL, NULL),
('sleep_schedule', '수면', '수면 패턴은?', 'Sleep pattern?', 'choice', '[{"value": "early_bird", "text_ko": "아침형", "text_en": "Early bird", "match_weight": 1.0}, {"value": "moderate", "text_ko": "보통", "text_en": "Moderate", "match_weight": 0.8}, {"value": "night_owl", "text_ko": "저녁형", "text_en": "Night owl", "match_weight": 0.6}, {"value": "irregular", "text_ko": "불규칙", "text_en": "Irregular", "match_weight": 0.5}]'::jsonb, 0.70, 7.0, false, ARRAY['수면'], NULL, NULL),
('cleanliness', '청결', '청결도 기준은?', 'Cleanliness standard?', 'choice', '[{"value": "very_clean", "text_ko": "매우 깔끔", "text_en": "Very clean", "match_weight": 1.0}, {"value": "clean", "text_ko": "깔끔함", "text_en": "Clean", "match_weight": 0.9}, {"value": "moderate", "text_ko": "보통", "text_en": "Moderate", "match_weight": 0.7}, {"value": "relaxed", "text_ko": "여유로움", "text_en": "Relaxed", "match_weight": 0.5}]'::jsonb, 0.75, 7.6, false, ARRAY['청결'], NULL, NULL),
('introvert_extrovert', '성격', '성격 유형은?', 'Personality type?', 'choice', '[{"value": "extrovert", "text_ko": "외향적", "text_en": "Extrovert", "match_weight": 1.0}, {"value": "ambivert", "text_ko": "중간", "text_en": "Ambivert", "match_weight": 0.9}, {"value": "introvert", "text_ko": "내향적", "text_en": "Introvert", "match_weight": 0.7}]'::jsonb, 0.75, 7.8, false, ARRAY['성격'], NULL, NULL),

-- TEXT QUESTIONS (Q36-40)
('personal_values_lifestyle', '가치관', '당신의 일상과 삶에서 가장 중요하게 생각하는 가치는 무엇이며, 어떻게 실천하고 계신가요?', 'What values are most important in your daily life and how do you practice them?', 'text', '[]'::jsonb, 0.95, 9.9, false, ARRAY['가치관', '일상'], '예: 성실함을 중요하게 여겨 매일 아침 운동하고, 가족과의 시간을 우선시하며...', 400),
('ideal_relationship_dynamic', '연애관', '이상적인 연애 관계는 어떤 모습이라고 생각하시나요? 두 사람이 어떻게 함께 성장하길 바라시나요?', 'What does an ideal romantic relationship look like to you?', 'text', '[]'::jsonb, 0.95, 9.8, false, ARRAY['연애', '관계'], '예: 서로의 꿈을 응원하면서도 함께하는 시간을 소중히 여기고...', 350),
('future_life_vision', '미래', '5년 후, 10년 후 당신의 삶은 어떤 모습일까요? 파트너와 함께 이루고 싶은 것은?', 'What will your life look like in 5-10 years?', 'text', '[]'::jsonb, 0.90, 9.6, false, ARRAY['미래', '비전'], '예: 안정적인 직장에서 일하며 아이 둘과 함께 교외에 집을 마련하고...', 350),
('conflict_growth_philosophy', '성장', '관계에서 어려움이나 갈등이 생겼을 때, 어떻게 극복하고 성장해왔나요?', 'How have you overcome difficulties in relationships?', 'text', '[]'::jsonb, 0.90, 9.4, false, ARRAY['갈등', '성장'], '예: 과거엔 감정을 숨겼지만, 이제는 솔직하게 표현하고...', 350),
('life_philosophy_happiness', '행복', '당신에게 행복한 삶이란 무엇이며, 어떤 순간에 가장 만족감을 느끼시나요?', 'What is a happy life to you?', 'text', '[]'::jsonb, 0.85, 9.1, false, ARRAY['행복', '만족'], '예: 사랑하는 사람들과 함께 웃으며 식사할 때, 작은 목표를 이뤘을 때...', 300);

INSERT INTO question_performance (question_id)
SELECT id FROM questions
ON CONFLICT (question_id) DO NOTHING;
